# Generated by Django 2.2.7 on 2020-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('chung', 'CHUNG'), ('inox tấm', 'INOX TẤM'), ('inox cuộn', 'INOX CUỘN')], default='chung', max_length=355),
        ),
    ]
