# Generated by Django 2.2.7 on 2020-03-18 04:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355)),
                ('img', models.ImageField(upload_to='posts')),
                ('description', models.CharField(max_length=555)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
