# Generated by Django 2.2.7 on 2020-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.CharField(choices=[('còn hàng', 'CÒN HÀNG'), ('tạm hết hàng', 'TẠM HẾT HÀNG')], default='còn hàng', max_length=355),
        ),
    ]
