# Generated by Django 2.2.7 on 2020-03-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200331_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories'),
        ),
    ]
