# Generated by Django 2.2.7 on 2020-04-01 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200331_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categories'),
        ),
    ]
