# Generated by Django 2.2.7 on 2019-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemforu_itemlast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=100)),
                ('password_again', models.CharField(max_length=100)),
            ],
        ),
    ]
