# Generated by Django 2.2.7 on 2019-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=100)),
                ('remember', models.BooleanField()),
            ],
        ),
    ]
