# Generated by Django 2.2.7 on 2019-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item'),
        ),
        migrations.AddField(
            model_name='itemforu',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemforu',
            name='slug',
            field=models.SlugField(default='item'),
        ),
        migrations.AddField(
            model_name='itemlast',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlast',
            name='slug',
            field=models.SlugField(default='item'),
        ),
    ]
